services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    env_file:
      - ./.env

  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    environment:
      - NODE_ENV=development

volumes:
  node_modules:
